"""init

Revision ID: fb8885cddb9d
Revises: 
Create Date: 2022-06-09 15:45:44.570264

"""
from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8885cddb9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('telegram_fullname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_client_telegram_username'), 'client', ['telegram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_telegram_username'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
